//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.EmployeeTraining {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.EmployeeTraining.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can attend.
        /// </summary>
        public static string Audience {
            get {
                return ResourceManager.GetString("Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string AudiencePrivate {
            get {
                return ResourceManager.GetString("AudiencePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string AudiencePublic {
            get {
                return ResourceManager.GetString("AudiencePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been automatically registered for this event..
        /// </summary>
        public static string AutoRegisteredCardSubTitle {
            get {
                return ResourceManager.GetString("AutoRegisteredCardSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory event!.
        /// </summary>
        public static string AutoRegisteredHeader {
            get {
                return ResourceManager.GetString("AutoRegisteredHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add event.
        /// </summary>
        public static string BotCommandAddEvent {
            get {
                return ResourceManager.GetString("BotCommandAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live event URL: {0}.
        /// </summary>
        public static string CalendarEventLiveEventURLText {
            get {
                return ResourceManager.GetString("CalendarEventLiveEventURLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: {0}.
        /// </summary>
        public static string CalendarEventLocationText {
            get {
                return ResourceManager.GetString("CalendarEventLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We regret to inform you that the following event has been cancelled..
        /// </summary>
        public static string CancellationCardSubTitle {
            get {
                return ResourceManager.GetString("CancellationCardSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event cancelled!.
        /// </summary>
        public static string CancellationHeader {
            get {
                return ResourceManager.GetString("CancellationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close registration.
        /// </summary>
        public static string CloseRegistrationCardButton {
            get {
                return ResourceManager.GetString("CloseRegistrationCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string CreatedByLabel {
            get {
                return ResourceManager.GetString("CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add event.
        /// </summary>
        public static string CreateEventButtonWelcomeCard {
            get {
                return ResourceManager.GetString("CreateEventButtonWelcomeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new event.
        /// </summary>
        public static string CreateEventCardTitleText {
            get {
                return ResourceManager.GetString("CreateEventCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow&apos;s events.
        /// </summary>
        public static string DailyReminderCardTitle {
            get {
                return ResourceManager.GetString("DailyReminderCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; time.
        /// </summary>
        public static string DateAndTimeLabel {
            get {
                return ResourceManager.GetString("DateAndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabelCard {
            get {
                return ResourceManager.GetString("DescriptionLabelCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit event.
        /// </summary>
        public static string EditEventCardButton {
            get {
                return ResourceManager.GetString("EditEventCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audience value. It should be either 1 or 2.
        /// </summary>
        public static string ErrorEventAudienceInvalid {
            get {
                return ResourceManager.GetString("ErrorEventAudienceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event category is required.
        /// </summary>
        public static string ErrorEventCategoryRequired {
            get {
                return ResourceManager.GetString("ErrorEventCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event description length cannot be more than {0} letters.
        /// </summary>
        public static string ErrorEventDescriptionLength {
            get {
                return ResourceManager.GetString("ErrorEventDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event description is required.
        /// </summary>
        public static string ErrorEventDescriptionRequired {
            get {
                return ResourceManager.GetString("ErrorEventDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event end time must be greater than start time.
        /// </summary>
        public static string ErrorEventEndTimeInvalid {
            get {
                return ResourceManager.GetString("ErrorEventEndTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event end time is required.
        /// </summary>
        public static string ErrorEventEndTimeRequired {
            get {
                return ResourceManager.GetString("ErrorEventEndTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum participants value.
        /// </summary>
        public static string ErrorEventMaxParticipantsInvalid {
            get {
                return ResourceManager.GetString("ErrorEventMaxParticipantsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name is required.
        /// </summary>
        public static string ErrorEventNameRequired {
            get {
                return ResourceManager.GetString("ErrorEventNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event photo URL/Color is required.
        /// </summary>
        public static string ErrorEventPhotoOrColorRequired {
            get {
                return ResourceManager.GetString("ErrorEventPhotoOrColorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event photo URL must be in valid URL format.
        /// </summary>
        public static string ErrorEventPhotoURLInvalid {
            get {
                return ResourceManager.GetString("ErrorEventPhotoURLInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event start date must be future date.
        /// </summary>
        public static string ErrorEventStartDateInvalid {
            get {
                return ResourceManager.GetString("ErrorEventStartDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event start date is required.
        /// </summary>
        public static string ErrorEventStartDateRequired {
            get {
                return ResourceManager.GetString("ErrorEventStartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event start time is required.
        /// </summary>
        public static string ErrorEventStartTimeRequired {
            get {
                return ResourceManager.GetString("ErrorEventStartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid event type value. Event type should be in-between 1 to 3.
        /// </summary>
        public static string ErrorEventTypeInvalid {
            get {
                return ResourceManager.GetString("ErrorEventTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event venue cannot be more than {0} letters.
        /// </summary>
        public static string ErrorEventVenueInvalid {
            get {
                return ResourceManager.GetString("ErrorEventVenueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting venue is required.
        /// </summary>
        public static string ErrorEventVenueRequired {
            get {
                return ResourceManager.GetString("ErrorEventVenueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting URL must be in valid URL format.
        /// </summary>
        public static string ErrorMeetingLinkInvalid {
            get {
                return ResourceManager.GetString("ErrorMeetingLinkInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting link is required.
        /// </summary>
        public static string ErrorMeetingLinkRequired {
            get {
                return ResourceManager.GetString("ErrorMeetingLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try after some time..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event updated!.
        /// </summary>
        public static string EventUpdatedCardTitle {
            get {
                return ResourceManager.GetString("EventUpdatedCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export registration data.
        /// </summary>
        public static string ExportDetailsCardButton {
            get {
                return ResourceManager.GetString("ExportDetailsCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading image.
        /// </summary>
        public static string LoadingImageAltText {
            get {
                return ResourceManager.GetString("LoadingImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrations.
        /// </summary>
        public static string NumberOfRegistrations {
            get {
                return ResourceManager.GetString("NumberOfRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered participants.
        /// </summary>
        public static string RegisteredUsers {
            get {
                return ResourceManager.GetString("RegisteredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View registration.
        /// </summary>
        public static string ReminderCardRegisteredEventButton {
            get {
                return ResourceManager.GetString("ReminderCardRegisteredEventButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder!.
        /// </summary>
        public static string ReminderCardTitle {
            get {
                return ResourceManager.GetString("ReminderCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams meeting.
        /// </summary>
        public static string TeamsMeetingText {
            get {
                return ResourceManager.GetString("TeamsMeetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event type.
        /// </summary>
        public static string TrainingType {
            get {
                return ResourceManager.GetString("TrainingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-person.
        /// </summary>
        public static string TrainingTypeInPerson {
            get {
                return ResourceManager.GetString("TrainingTypeInPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live event.
        /// </summary>
        public static string TrainingTypeLiveEvent {
            get {
                return ResourceManager.GetString("TrainingTypeLiveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all events.
        /// </summary>
        public static string ViewAllEventsCardButton {
            get {
                return ResourceManager.GetString("ViewAllEventsCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next week events.
        /// </summary>
        public static string WeeklyReminderCardTitle {
            get {
                return ResourceManager.GetString("WeeklyReminderCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to get started? Select {0} below:.
        /// </summary>
        public static string WelcomeCardPersonalContentFooter {
            get {
                return ResourceManager.GetString("WelcomeCardPersonalContentFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string WelcomeCardPersonalDiscoverButtonText {
            get {
                return ResourceManager.GetString("WelcomeCardPersonalDiscoverButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking forward to discover and participate in new events? I am here to help you discover new events, participate in them &amp; keep track of their occurance. So, lets get started!.
        /// </summary>
        public static string WelcomeCardPersonalIntro {
            get {
                return ResourceManager.GetString("WelcomeCardPersonalIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Discover &amp; explore all events..
        /// </summary>
        public static string WelcomeCardPersonalPoint1 {
            get {
                return ResourceManager.GetString("WelcomeCardPersonalPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Register to the events you like..
        /// </summary>
        public static string WelcomeCardPersonalPoint2 {
            get {
                return ResourceManager.GetString("WelcomeCardPersonalPoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Keep a track of all your completed events..
        /// </summary>
        public static string WelcomeCardPersonalPoint3 {
            get {
                return ResourceManager.GetString("WelcomeCardPersonalPoint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Get notified about all your activities &amp; receive reminders of your upcoming registered events..
        /// </summary>
        public static string WelcomeCardPersonalPoint4 {
            get {
                return ResourceManager.GetString("WelcomeCardPersonalPoint4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to get started? Select {0} below:.
        /// </summary>
        public static string WelcomeCardTeamContentFooter {
            get {
                return ResourceManager.GetString("WelcomeCardTeamContentFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifically, I can help you:.
        /// </summary>
        public static string WelcomeCardTeamHeading {
            get {
                return ResourceManager.GetString("WelcomeCardTeamHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m the Employee Training bot, and I can help you make the most of the learning opportunites offered by your org..
        /// </summary>
        public static string WelcomeCardTeamIntro {
            get {
                return ResourceManager.GetString("WelcomeCardTeamIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Explore all upcoming training events.
        /// </summary>
        public static string WelcomeCardTeamPoint1 {
            get {
                return ResourceManager.GetString("WelcomeCardTeamPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Register for events.
        /// </summary>
        public static string WelcomeCardTeamPoint2 {
            get {
                return ResourceManager.GetString("WelcomeCardTeamPoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Keep a track of completed training.
        /// </summary>
        public static string WelcomeCardTeamPoint3 {
            get {
                return ResourceManager.GetString("WelcomeCardTeamPoint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Get helpful notification and reminders.
        /// </summary>
        public static string WelcomeCardTeamPoint4 {
            get {
                return ResourceManager.GetString("WelcomeCardTeamPoint4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
    }
}
